version: '3.4'

services:

  server:
    build: ./server
    image: ${SERVICE_NAME}
    command: /usr/app/node_modules/.bin/nodemon src/index.js
    container_name: ${SERVICE_NAME}
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    networks:
      - back_end

  db:
    image: mongo:latest
    container_name: ${MONGO_CRUD_DB_URL}
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_CRUD_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_CRUD_DB_PASS}
    volumes:
      - financiera_mongo_data:/data/db
    ports:
      - ${DB_PORT}:27017
    networks:
      - back_end

  mongoexpress:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_CRUD_DB_URL}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_CRUD_DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_CRUD_DB_PASS}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8090:8081
    depends_on:
      - db
    networks:
      - back_end

volumes:
  gosrc:
  financiera_mongo_data:
networks:
  back_end:
    external: true